In [1]:
import pandas as pd

In [2]:
import openpyxl

In [5]:
pd.read_csv("Serbia-traffic-accidents-16-26-for-work-ENG.xlsx - all.csv")

,SN,City,Date & Time,Damage,Type of accident
0,1106801,BEOGRAD,"01.10.2015,12:05",Material damage,TA with one vehicle
1,1106289,BEOGRAD,"03.10.2015,12:00",Injuries,TA with at least 2 vehicles - no turn
2,1106903,BEOGRAD,"08.10.2015,20:00",Material damage,TA with one vehicle
3,1106338,BEOGRAD,"11.10.2015,20:40",Material damage,TA with one vehicle
4,1106747,BEOGRAD,"14.10.2015,19:10",Material damage,TA with at least 2 vehicles - no turn
...,...,...,...,...,...
356018,1576167,ŠABAC,"25.05.2026,15:10",Material damage,TA with parked vehicles
356019,1576480,ŠABAC,"26.05.2026,11:00",Injuries,TA with parked vehicles
356020,1576502,ŠABAC,"26.05.2026,20:05",Injuries,TA with at least 2 vehicles - no turn
356021,1576585,ŠABAC,"27.05.2026,09:20",Injuries,TA with pedestrians
356022,1576903,ŠABAC,"29.05.2026,20:55",Injuries,TA with at least 2 vehicles – turning or crossing

In [6]:
df=pd.read_csv("Serbia-traffic-accidents-16-26-for-work-ENG.xlsx - all.csv")

Basic data

In [7]:
Damage = df['Damage'].value_counts()

In [8]:
Accident_type = df['Type of accident'].value_counts()

In [9]:
Location = df['City'].value_counts()

In [10]:
Damage_per_type = df.pivot_table(index='Type of accident', columns='Damage', values='SN', aggfunc='count')
Damage_per_type

Damage,Death,Injuries,Material damage
Type of accident,,,
TA with at least 2 vehicles - no turn,1302,42387,67874
TA with at least 2 vehicles – turning or crossing,776,39272,46404
TA with one vehicle,1696,27495,48177
TA with parked vehicles,126,3779,48529
TA with pedestrians,1340,26443,423

DATE & TIME cleaning

In [11]:
df['Date & Time'] = pd.to_datetime(df['Date & Time'])
df['Date'] = df['Date & Time'].dt.date
df['Time'] = df['Date & Time'].dt.time

/var/folders/5_/w6x2qs2n2dsg6mgnhkrxnzg00000gn/T/ipykernel_1648/3166515630.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date & Time'] = pd.to_datetime(df['Date & Time'])

In [12]:
df.head()

,SN,City,Date & Time,Damage,Type of accident,Date,Time
0,1106801,BEOGRAD,2015-01-10 12:05:00,Material damage,TA with one vehicle,2015-01-10,12:05:00
1,1106289,BEOGRAD,2015-03-10 12:00:00,Injuries,TA with at least 2 vehicles - no turn,2015-03-10,12:00:00
2,1106903,BEOGRAD,2015-08-10 20:00:00,Material damage,TA with one vehicle,2015-08-10,20:00:00
3,1106338,BEOGRAD,2015-11-10 20:40:00,Material damage,TA with one vehicle,2015-11-10,20:40:00
4,1106747,BEOGRAD,2015-10-14 19:10:00,Material damage,TA with at least 2 vehicles - no turn,2015-10-14,19:10:00

In [13]:
df['Date'] = pd.to_datetime(df['Date'])
df['Month_Day'] = df['Date'].dt.strftime('%m-%d')
df

,SN,City,Date & Time,Damage,Type of accident,Date,Time,Month_Day
0,1106801,BEOGRAD,2015-01-10 12:05:00,Material damage,TA with one vehicle,2015-01-10,12:05:00,01-10
1,1106289,BEOGRAD,2015-03-10 12:00:00,Injuries,TA with at least 2 vehicles - no turn,2015-03-10,12:00:00,03-10
2,1106903,BEOGRAD,2015-08-10 20:00:00,Material damage,TA with one vehicle,2015-08-10,20:00:00,08-10
3,1106338,BEOGRAD,2015-11-10 20:40:00,Material damage,TA with one vehicle,2015-11-10,20:40:00,11-10
4,1106747,BEOGRAD,2015-10-14 19:10:00,Material damage,TA with at least 2 vehicles - no turn,2015-10-14,19:10:00,10-14
...,...,...,...,...,...,...,...,...
356018,1576167,ŠABAC,2026-05-25 15:10:00,Material damage,TA with parked vehicles,2026-05-25,15:10:00,05-25
356019,1576480,ŠABAC,2026-05-26 11:00:00,Injuries,TA with parked vehicles,2026-05-26,11:00:00,05-26
356020,1576502,ŠABAC,2026-05-26 20:05:00,Injuries,TA with at least 2 vehicles - no turn,2026-05-26,20:05:00,05-26
356021,1576585,ŠABAC,2026-05-27 09:20:00,Injuries,TA with pedestrians,2026-05-27,09:20:00,05-27
356022,1576903,ŠABAC,2026-05-29 20:55:00,Injuries,TA with at least 2 vehicles – turning or crossing,2026-05-29,20:55:00,05-29

In [14]:
df['Date'] = pd.to_datetime(df['Date'])
df['Weekday'] = df['Date'].dt.day_name()
df

,SN,City,Date & Time,Damage,Type of accident,Date,Time,Month_Day,Weekday
0,1106801,BEOGRAD,2015-01-10 12:05:00,Material damage,TA with one vehicle,2015-01-10,12:05:00,01-10,Saturday
1,1106289,BEOGRAD,2015-03-10 12:00:00,Injuries,TA with at least 2 vehicles - no turn,2015-03-10,12:00:00,03-10,Tuesday
2,1106903,BEOGRAD,2015-08-10 20:00:00,Material damage,TA with one vehicle,2015-08-10,20:00:00,08-10,Monday
3,1106338,BEOGRAD,2015-11-10 20:40:00,Material damage,TA with one vehicle,2015-11-10,20:40:00,11-10,Tuesday
4,1106747,BEOGRAD,2015-10-14 19:10:00,Material damage,TA with at least 2 vehicles - no turn,2015-10-14,19:10:00,10-14,Wednesday
...,...,...,...,...,...,...,...,...,...
356018,1576167,ŠABAC,2026-05-25 15:10:00,Material damage,TA with parked vehicles,2026-05-25,15:10:00,05-25,Monday
356019,1576480,ŠABAC,2026-05-26 11:00:00,Injuries,TA with parked vehicles,2026-05-26,11:00:00,05-26,Tuesday
356020,1576502,ŠABAC,2026-05-26 20:05:00,Injuries,TA with at least 2 vehicles - no turn,2026-05-26,20:05:00,05-26,Tuesday
356021,1576585,ŠABAC,2026-05-27 09:20:00,Injuries,TA with pedestrians,2026-05-27,09:20:00,05-27,Wednesday
356022,1576903,ŠABAC,2026-05-29 20:55:00,Injuries,TA with at least 2 vehicles – turning or crossing,2026-05-29,20:55:00,05-29,Friday

In [15]:
df['Month'] = df['Date'].dt.month_name()
df

,SN,City,Date & Time,Damage,Type of accident,Date,Time,Month_Day,Weekday,Month
0,1106801,BEOGRAD,2015-01-10 12:05:00,Material damage,TA with one vehicle,2015-01-10,12:05:00,01-10,Saturday,January
1,1106289,BEOGRAD,2015-03-10 12:00:00,Injuries,TA with at least 2 vehicles - no turn,2015-03-10,12:00:00,03-10,Tuesday,March
2,1106903,BEOGRAD,2015-08-10 20:00:00,Material damage,TA with one vehicle,2015-08-10,20:00:00,08-10,Monday,August
3,1106338,BEOGRAD,2015-11-10 20:40:00,Material damage,TA with one vehicle,2015-11-10,20:40:00,11-10,Tuesday,November
4,1106747,BEOGRAD,2015-10-14 19:10:00,Material damage,TA with at least 2 vehicles - no turn,2015-10-14,19:10:00,10-14,Wednesday,October
...,...,...,...,...,...,...,...,...,...,...
356018,1576167,ŠABAC,2026-05-25 15:10:00,Material damage,TA with parked vehicles,2026-05-25,15:10:00,05-25,Monday,May
356019,1576480,ŠABAC,2026-05-26 11:00:00,Injuries,TA with parked vehicles,2026-05-26,11:00:00,05-26,Tuesday,May
356020,1576502,ŠABAC,2026-05-26 20:05:00,Injuries,TA with at least 2 vehicles - no turn,2026-05-26,20:05:00,05-26,Tuesday,May
356021,1576585,ŠABAC,2026-05-27 09:20:00,Injuries,TA with pedestrians,2026-05-27,09:20:00,05-27,Wednesday,May
356022,1576903,ŠABAC,2026-05-29 20:55:00,Injuries,TA with at least 2 vehicles – turning or crossing,2026-05-29,20:55:00,05-29,Friday,May

In [16]:
df['Year'] = df['Date'].dt.year
df

,SN,City,Date & Time,Damage,Type of accident,Date,Time,Month_Day,Weekday,Month,Year
0,1106801,BEOGRAD,2015-01-10 12:05:00,Material damage,TA with one vehicle,2015-01-10,12:05:00,01-10,Saturday,January,2015
1,1106289,BEOGRAD,2015-03-10 12:00:00,Injuries,TA with at least 2 vehicles - no turn,2015-03-10,12:00:00,03-10,Tuesday,March,2015
2,1106903,BEOGRAD,2015-08-10 20:00:00,Material damage,TA with one vehicle,2015-08-10,20:00:00,08-10,Monday,August,2015
3,1106338,BEOGRAD,2015-11-10 20:40:00,Material damage,TA with one vehicle,2015-11-10,20:40:00,11-10,Tuesday,November,2015
4,1106747,BEOGRAD,2015-10-14 19:10:00,Material damage,TA with at least 2 vehicles - no turn,2015-10-14,19:10:00,10-14,Wednesday,October,2015
...,...,...,...,...,...,...,...,...,...,...,...
356018,1576167,ŠABAC,2026-05-25 15:10:00,Material damage,TA with parked vehicles,2026-05-25,15:10:00,05-25,Monday,May,2026
356019,1576480,ŠABAC,2026-05-26 11:00:00,Injuries,TA with parked vehicles,2026-05-26,11:00:00,05-26,Tuesday,May,2026
356020,1576502,ŠABAC,2026-05-26 20:05:00,Injuries,TA with at least 2 vehicles - no turn,2026-05-26,20:05:00,05-26,Tuesday,May,2026
356021,1576585,ŠABAC,2026-05-27 09:20:00,Injuries,TA with pedestrians,2026-05-27,09:20:00,05-27,Wednesday,May,2026
356022,1576903,ŠABAC,2026-05-29 20:55:00,Injuries,TA with at least 2 vehicles – turning or crossing,2026-05-29,20:55:00,05-29,Friday,May,2026

DATE & TIME analysis

In [17]:
Sort_by_specific_date = (
    df
    ["Date"]
    .value_counts()
    .to_frame("SN")
)
Sort_by_specific_date.head()

             SN
Date
2018-12-14  170
2018-02-26  161
2024-12-23  161
2017-11-09  160
2019-12-23  160

In [18]:
Sort_by_date_in_years = (
    df
    ["Month_Day"]
    .value_counts()
    .to_frame("SN")
)
Sort_by_date_in_years.head(10)

             SN
Month_Day
12-30      1296
12-23      1270
12-29      1267
12-28      1255
12-25      1237
12-31      1223
12-24      1215
12-27      1172
10-10      1151
12-26      1146

In [19]:
Sort_by_year = (
    df
    ["Year"]
    .value_counts()
    .to_frame("SN")
)
Sort_by_year

         SN
Year
2017  36672
2018  35993
2019  35956
2021  34751
2025  33415
2022  33399
2023  32974
2024  32330
2020  30891
2016  29402
2026  13477
2015   6763

In [20]:
Sort_by_time = (
    df
    ["Time"]
    .value_counts()
    .to_frame("SN")
)
Sort_by_time.head(10)

            SN
Time
13:00:00  5117
14:00:00  4989
17:00:00  4917
15:00:00  4815
16:00:00  4706
18:00:00  4579
12:00:00  4555
11:00:00  4354
13:30:00  4082
16:30:00  4076

In [21]:
Sort_by_weekday = (
    df
    ["Weekday"]
    .value_counts()
    .to_frame("SN")
)
Sort_by_weekday

              SN
Weekday
Friday     54221
Thursday   52086
Monday     51892
Wednesday  50921
Saturday   50577
Tuesday    50114
Sunday     46212

In [22]:
Sort_by_month = (
    df
    ["Month"]
    .value_counts()
    .to_frame("SN")
)
Sort_by_month

              SN
Month
December   32770
October    31863
May        31143
September  30228
November   29746
August     29353
April      29200
July       29061
January    29008
March      28997
June       28809
February   25845

In [23]:
df.to_csv("EDITOVANO1.csv", index=False)

ANALYSIS

In [24]:
Damage_per_type = df.pivot_table(index='Type of accident', columns='Damage', values='SN', aggfunc='count')
Damage_per_type

Damage,Death,Injuries,Material damage
Type of accident,,,
TA with at least 2 vehicles - no turn,1302,42387,67874
TA with at least 2 vehicles – turning or crossing,776,39272,46404
TA with one vehicle,1696,27495,48177
TA with parked vehicles,126,3779,48529
TA with pedestrians,1340,26443,423

In [25]:
Damage_per_weekday = df.pivot_table(index='Weekday', columns='Damage', values='SN', aggfunc='count')
Damage_per_weekday

Damage     Death  Injuries  Material damage
Weekday
Friday       773     21483            31965
Monday       697     20279            30916
Saturday     831     19863            29883
Sunday       788     18319            27105
Thursday     745     20396            30945
Tuesday      685     19467            29962
Wednesday    721     19569            30631

In [26]:
Damage_per_month = df.pivot_table(index='Month', columns='Damage', values='SN', aggfunc='count')
Damage_per_month

Damage     Death  Injuries  Material damage
Month
April        386     11371            17443
August       493     12111            16749
December     493     11972            20305
February     346      9691            15808
January      402     10505            18101
July         455     11987            16619
June         437     11794            16578
March        398     10807            17792
May          396     12434            18313
November     443     11607            17696
October      478     12901            18484
September    513     12196            17519

In [27]:
Damage_per_dates = df.pivot_table(index='Month_Day', columns='Damage', values='SN', aggfunc='count')
Damage_per_dates.head()

Damage     Death  Injuries  Material damage
Month_Day
01-01         14       286              546
01-02         18       315              570
01-03         12       325              548
01-04         12       367              611
01-05         20       387              425

In [28]:
Type_per_weekday = df.pivot_table(index='Weekday', columns='Type of accident', values='SN', aggfunc='count')
Type_per_weekday

Type of accident,TA with at least 2 vehicles - no turn,TA with at least 2 vehicles – turning or crossing,TA with one vehicle,TA with parked vehicles,TA with pedestrians
Weekday,,,,,
Friday,17499,13371,11222,7594,4535
Monday,16715,12680,10646,7558,4293
Saturday,15358,12031,11979,7607,3602
Sunday,13388,10555,12113,7113,3043
Thursday,16564,12942,10660,7593,4327
Tuesday,15995,12160,10246,7511,4202
Wednesday,16044,12713,10502,7458,4204

In [29]:
Type_per_month = df.pivot_table(index='Month', columns='Type of accident', values='SN', aggfunc='count')
Type_per_month

Type of accident,TA with at least 2 vehicles - no turn,TA with at least 2 vehicles – turning or crossing,TA with one vehicle,TA with parked vehicles,TA with pedestrians
Month,,,,,
April,9027,7187,6542,4296,2148
August,9205,7259,6731,4174,1984
December,10380,7572,7099,4809,2910
February,7988,6116,5706,3901,2134
January,8798,6547,6782,4472,2409
July,9164,7194,6605,4194,1904
June,8988,7170,6353,4208,2090
March,8956,7058,6339,4392,2252
May,9528,7800,6533,4843,2439
November,9412,7196,5994,4237,2907
October,10365,7893,6356,4508,2741
September,9752,7460,6328,4400,2288